### ISSUE TITLE
When I visit the link the input and title animate to the right 

### ISSUE THREAD

**Issue by trc5019** [fac-12/nasa-daily#18]
![nasa](https://user-images.githubusercontent.com/29644807/33205887-66cb5662-d100-11e7-8482-1248e9586054.gif)

**Comment by Jbarget** [comment]
its cos of this stuff :) 

![screen shot 2017-11-24 at 10 23 44](https://user-images.githubusercontent.com/11725595/33206268-92b0222a-d101-11e7-8a2a-538736d415a5.png)

**Comment by trc5019** [comment]
Don't worry it was just my browser

**Comment by Jbarget** [comment]
@trc5019 no it wasn't i had the same issues :), think you can reopen the issue
