### ISSUE TITLE
Testing APIs

### ISSUE THREAD

**Issue by astroash** [fac-12/nasa-daily#37]
https://github.com/fac-12/nasa-daily/blob/40cb540bf94ca0abb1b0d0df46e9383a38f080d5/src/test.js#L50-L56

You don't need to test sending off a request to an api as you started to do here, instead you would use a module called [knock](https://www.npmjs.com/package/knock). I wouldn't worry about using this just yet, but when you're feeling more comfortable with testing this is the way to go 😸

**Comment by Dragomirc** [comment]
As per @astroash the correct link is https://github.com/node-nock/nock
